fix: for yahoo time not in UTC
jshor/datebook pull request #153
Opened 2021-05-03 15:17 UTC by TiberioG

I had problems with yahoo calendar links, only in Yahoo the displayed time was not correct in my timezone, whereas on Google it was displayed correctly.
So I have changed the way to formatDate only for Yahoo.

2021-05-03 23:09 UTC, jshor commented
@TiberioG thanks for the PR. It does indeed appear that Yahoo calendar doesn't respect UTC dates (it completely ignores the trailing `Z`) and [has been reported by others as well](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/yahoo.md#st).

A few things need to be done in this PR, but I'll merge it once they're completed

2021-05-03 23:12 UTC, jshor requested changes

2021-05-03 23:12 UTC, jshor commented on src/utils/time.ts
> +    YYYY: d.getUTCFullYear(),
- [ ] change to `getFullYear()`

2021-05-03 23:12 UTC, jshor commented on src/YahooCalendar.ts
> +      this.setParam('st', time.formatDateNoUtc(this.start, FORMAT.FULL))
`FORMAT.FULL` includes the `Z` at the end, which signifies that it's a UTC timestamp. It seems to work anyway (Yahoo just ignores it completely), but better safe to make a new constant for this

- [ ] add new const (`FORMAT.NO_UTC_FULL`?)

2021-05-03 23:12 UTC, jshor commented on src/utils/time.ts
> +const formatDateNoUtc = (d: Date = new Date(), format: string): string => {
- [ ] write unit test for `formatDateNoUtc()`

2021-05-04 09:39 UTC, TiberioG commented
ok sure, I changed as requested, glad you appreciated my contribution

2021-05-04 13:25 UTC, jshor approved these changes

2021-05-04 13:25 UTC, merged